### ISSUE TITLE
Widgets not showing

### ISSUE THREAD

**Issue by davidcreator** [the-turk/flarum-welcome-widgets#3]
I have followed the installation steps and when activated the widgets are not shown.

**Comment by the-turk** [comment]
Try to logout and login again.

**Comment by davidcreator** [comment]
I have tried disconnecting and logging in again but it still doesn't show the widgets

**Comment by the-turk** [comment]
Please check your browser's console (Firefox: CTRL + SHIFT + K) for errors.

Can you share your Flarum's URL?

**Comment by davidcreator** [comment]
I have been investigating what the possible causes were and I have been able to verify that the widgets do not show if you log in with Google, FaceBook or Twitter. Logging in normally if you get to teach them. URL: https://foro.paranoiasgamers.com

**Comment by the-turk** [comment]
Thanks for the report, I'll see what I can do.

**Comment by the-turk** [comment]
https://github.com/flarum/core/issues/1994

It seems like the `LoggedIn` event for users isn't dispatched when logging in via an external identity provider. So we probably will wait for that to be fixed.
